#
# Makefile
#
# Copyright 2019-2020 MicroEJ Corp. All rights reserved.
# This library is provided in source code for use, modification and test, subject to license terms.
# Any modification of the source code will break MicroEJ Corp. warranties on the whole library.
#

CFLAGS += -DHAS_BDROID_BUILDCFG # Define specific MicroEJ specification for bluedroid stack
CFLAGS += -DMBEDTLS_USER_CONFIG_FILE=\"microej_mbedtls_config.h\" # Define specific MicroEJ specification for mbedtls stack
