/* 
 * IceTea
 * 
 * Copyright 2014-2020 MicroEJ Corp. All rights reserved.
 * This library is provided in source code for use, modification and test, subject to license terms.
 * Any modification of the source code will break MicroEJ Corp. warranties on the whole library.
 */
/* 
 * AUTOGENERATED by Unknown product - Unknown version - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#include <stdint.h>
#define LLCOMM_CONCAT0(p,s) p ## s
#define LLCOMM_CONCAT(p,s) LLCOMM_CONCAT0(p,s)
#define LLCOMM_IMPL_initialize LLCOMM_CONCAT(LLCOMM_IMPL,_initialize)
#define LLCOMM_IMPL_syncConnectionsEnter LLCOMM_CONCAT(LLCOMM_IMPL,_syncConnectionsEnter)
#define LLCOMM_IMPL_syncConnectionsExit LLCOMM_CONCAT(LLCOMM_IMPL,_syncConnectionsExit)
LLCOMM LLCOMM_getSingleton_instance;

/* 
 * Get the unique instance of this type within the system.
 */
LLCOMM* LLCOMM_IMPL_getSingleton(void)
{
	return &LLCOMM_getSingleton_instance;
}
