/* 
 * Copyright 2011-2014 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by Unknown product - Unknown version - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
typedef struct LLBSP LLBSP;
#include <stdint.h>
#define LLBSP_CONCAT0(p,s) p ## s
#define LLBSP_CONCAT(p,s) LLBSP_CONCAT0(p,s)
#define LLBSP_IMPL_isInReadOnlyMemory LLBSP_CONCAT(LLBSP_IMPL,_isInReadOnlyMemory__LiceTea_lang_Ram_2)
#define LLBSP_IMPL_putchar LLBSP_CONCAT(LLBSP_IMPL,_putchar__I)
struct LLBSP
{
	int32_t __icetea__id__;
};
LLBSP LLBSP_getSingleton_instance;

/* 
 * Get the unique instance of this type within the system.
 */
LLBSP* LLBSP_IMPL_getSingleton(void)
{
	return &LLBSP_getSingleton_instance;
}
