/* 
 * IceTea
 * 
 * Copyright 2013-2016 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * This file is auto-generated - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#ifndef _LLCOMM_CONNECTION_intern
#define _LLCOMM_CONNECTION_intern 
typedef struct LLCOMM_CONNECTION LLCOMM_CONNECTION;
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
#define LLCOMM_CONNECTION_close __icetea__virtual__com_is2t_comm_StaticCommStream___close
#define LLCOMM_CONNECTION_isClosed __icetea__virtual__com_is2t_comm_StaticCommStream___isClosed
#define LLCOMM_CONNECTION_enableRead __icetea__virtual__com_is2t_comm_StaticCommStream___enableRead
#define LLCOMM_CONNECTION_enableWrite __icetea__virtual__com_is2t_comm_StaticCommStream___enableWrite
#define LLCOMM_CONNECTION_closeRead __icetea__virtual__com_is2t_comm_StaticCommStream___closeRead
#define LLCOMM_CONNECTION_closeWrite __icetea__virtual__com_is2t_comm_StaticCommStream___closeWrite
#define LLCOMM_CONNECTION_available __icetea__virtual__com_is2t_comm_StaticCommStream___available
#define LLCOMM_CONNECTION_read __icetea__virtual__com_is2t_comm_StaticCommStream___read
#define LLCOMM_CONNECTION_write __icetea__virtual__com_is2t_comm_StaticCommStream___write__I
#define LLCOMM_CONNECTION_flush __icetea__virtual__com_is2t_comm_StaticCommStream___flush
#define LLCOMM_CONNECTION_initialize __icetea__virtual__com_is2t_comm_StaticCommStream___initialize
#define LLCOMM_CONNECTION_configure __icetea__virtual__com_is2t_comm_StaticCommStream___configure__IIII
#define LLCOMM_CONNECTION_enableRX __icetea__virtual__com_is2t_comm_StaticCommStream___enableRX
#define LLCOMM_CONNECTION_disableRX __icetea__virtual__com_is2t_comm_StaticCommStream___disableRX
#define LLCOMM_CONNECTION_enableRXDeviceInterrupt __icetea__virtual__com_is2t_comm_StaticCommStream___enableRXDeviceInterrupt
#define LLCOMM_CONNECTION_disableRXDeviceInterrupt __icetea__virtual__com_is2t_comm_StaticCommStream___disableRXDeviceInterrupt
#define LLCOMM_CONNECTION_enableTX __icetea__virtual__com_is2t_comm_StaticCommStream___enableTX
#define LLCOMM_CONNECTION_disableTX __icetea__virtual__com_is2t_comm_StaticCommStream___disableTX
#define LLCOMM_CONNECTION_enableTXDeviceInterrupt __icetea__virtual__com_is2t_comm_StaticCommStream___enableTXDeviceInterrupt
#define LLCOMM_CONNECTION_disableTXDeviceInterrupt __icetea__virtual__com_is2t_comm_StaticCommStream___disableTXDeviceInterrupt
#define LLCOMM_CONNECTION_configureDevice __icetea__virtual__com_is2t_comm_StaticCommStream___configureDevice__IIII
#define LLCOMM_CONNECTION_getName __icetea__virtual__com_is2t_comm_StaticCommStream___getName
#define LLCOMM_CONNECTION_getPlatformId __icetea__virtual__com_is2t_comm_StaticCommStream___getPlatformId
#define LLCOMM_CONNECTION_released __icetea__virtual__com_is2t_comm_StaticCommStream___released
#define LLCOMM_CONNECTION_getNbProperties __icetea__virtual__com_is2t_comm_StaticCommStream___getNbProperties
#define LLCOMM_CONNECTION_getProperty __icetea__virtual__com_is2t_comm_StaticCommStream___getProperty__LiceTea_lang_Ram_2
#define LLCOMM_CONNECTION_getPropertyName __icetea__virtual__com_is2t_comm_StaticCommStream___getPropertyName__I
struct LLCOMM_CONNECTION
{
	int32_t __icetea__id__;
	int32_t _reserved0;
	int8_t _reserved1;
	int8_t _reserved2;
	int8_t _reserved3;
	int8_t counter;
};
#ifdef __cplusplus
	}
#endif
#endif
