/* 
 * IceTea
 * 
 * Copyright 2012-2019 MicroEJ Corp. All rights reserved.
 * MicroEJ Corp. PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by Unknown product - Unknown version - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#ifndef _LLDISPLAY_DECODER_intern
#define _LLDISPLAY_DECODER_intern 
typedef struct LLDISPLAY_DECODER LLDISPLAY_DECODER;
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
struct LLDISPLAY_DECODER
{
	int32_t __icetea__id__;
};
#ifdef __cplusplus
	}
#endif
#endif
