/*
 * C
 *
 * Copyright 2016-2020 MicroEJ Corp. All rights reserved.
 * This library is provided in source code for use, modification and test, subject to license terms.
 * Any modification of the source code will break MicroEJ Corp. warranties on the whole library.
 */

/**
 * @file
 * @brief MicroEJ ECOM-NETWORK low level API
 * @author MicroEJ Developer Team
 * @version 1.1.0
 * @date 23 November 2020
 */

#define LLECOM_NETWORK_IMPL_disable Java_ej_ecom_network_natives_InterfaceManagerImplNatives_disable
#define LLECOM_NETWORK_IMPL_enable Java_ej_ecom_network_natives_InterfaceManagerImplNatives_enable
#define LLECOM_NETWORK_IMPL_isEnabled Java_ej_ecom_network_natives_InterfaceManagerImplNatives_isEnabled
#define LLECOM_NETWORK_IMPL_start Java_ej_ecom_network_natives_InterfaceManagerImplNatives_start
#define LLECOM_NETWORK_IMPL_stop Java_ej_ecom_network_natives_InterfaceManagerImplNatives_stop
#define LLECOM_NETWORK_IMPL_isStarted Java_ej_ecom_network_natives_InterfaceManagerImplNatives_isStarted
#define LLECOM_NETWORK_IMPL_getDNSCount Java_ej_ecom_network_natives_InterfaceManagerImplNatives_getDNSCount
#define LLECOM_NETWORK_IMPL_getDNS Java_ej_ecom_network_natives_InterfaceManagerImplNatives_getDNS
#define LLECOM_NETWORK_IMPL_getGateway Java_ej_ecom_network_natives_InterfaceManagerImplNatives_getGateway
#define LLECOM_NETWORK_IMPL_getNetmask Java_ej_ecom_network_natives_InterfaceManagerImplNatives_getNetmask
#define LLECOM_NETWORK_IMPL_isDNSStatic Java_ej_ecom_network_natives_InterfaceManagerImplNatives_isDNSStatic
#define LLECOM_NETWORK_IMPL_isStatic Java_ej_ecom_network_natives_InterfaceManagerImplNatives_isStatic
#define LLECOM_NETWORK_IMPL_endConfiguration Java_ej_ecom_network_natives_InterfaceManagerImplNatives_endConfiguration
#define LLECOM_NETWORK_IMPL_startConfiguration Java_ej_ecom_network_natives_InterfaceManagerImplNatives_startConfiguration
#define LLECOM_NETWORK_IMPL_setDNS Java_ej_ecom_network_natives_InterfaceManagerImplNatives_setDNS
#define LLECOM_NETWORK_IMPL_setGateway Java_ej_ecom_network_natives_InterfaceManagerImplNatives_setGateway
#define LLECOM_NETWORK_IMPL_setIP Java_ej_ecom_network_natives_InterfaceManagerImplNatives_setIP
#define LLECOM_NETWORK_IMPL_setNetmask Java_ej_ecom_network_natives_InterfaceManagerImplNatives_setNetmask
#define LLECOM_NETWORK_IMPL_useDHCP Java_ej_ecom_network_natives_InterfaceManagerImplNatives_useDHCP
#define LLECOM_NETWORK_IMPL_useStaticDNS Java_ej_ecom_network_natives_InterfaceManagerImplNatives_useStaticDNS
#define LLECOM_NETWORK_IMPL_setDefault Java_ej_ecom_network_natives_InterfaceManagerImplNatives_setDefault
