/*
 * C
 *
 * Copyright 2016-2021 MicroEJ Corp. All rights reserved.
 * This library is provided in source code for use, modification and test, subject to license terms.
 * Any modification of the source code will break MicroEJ Corp. warranties on the whole library.
 */

/**
 * @file
 * @brief MicroEJ ECOM-WIFI low level API
 * @author MicroEJ Developer Team
 * @version 1.2.0
 * @date 17 June 2021
 */

#define LLECOM_WIFI_IMPL_disableSoftAP Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_disableSoftAP
#define LLECOM_WIFI_IMPL_enableSoftAP Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_enableSoftAP
#define LLECOM_WIFI_IMPL_setNameSoftAP Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_setNameSoftAP
#define LLECOM_WIFI_IMPL_getBSSID Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getBSSID
#define LLECOM_WIFI_IMPL_getChannel Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getChannel
#define LLECOM_WIFI_IMPL_getClientState Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getClientState
#define LLECOM_WIFI_IMPL_getAccessPointState Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getAccessPointState
#define LLECOM_WIFI_IMPL_getRSSI Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getRSSI
#define LLECOM_WIFI_IMPL_getSecurityMode Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getSecurityMode
#define LLECOM_WIFI_IMPL_getSSID Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getSSID
#define LLECOM_WIFI_IMPL_getWPSModes Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getWPSModes
#define LLECOM_WIFI_IMPL_join Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_join
#define LLECOM_WIFI_IMPL_joinWithSecurityMode Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_joinWithSecurityMode
#define LLECOM_WIFI_IMPL_leave Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_leave
#define LLECOM_WIFI_IMPL_scanAPCount Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_scanAPCount
#define LLECOM_WIFI_IMPL_scanAPssidAt Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_scanAPssidAt
#define LLECOM_WIFI_IMPL_scanAPbssidAt Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_scanAPbssidAt
#define LLECOM_WIFI_IMPL_scanAPbssidAt Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_scanAPbssidAt
#define LLECOM_WIFI_IMPL_scanAPchannelAt Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_scanAPchannelAt
#define LLECOM_WIFI_IMPL_scanAPrssiAt Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_scanAPrssiAt
#define LLECOM_WIFI_IMPL_scanAPsecurityModeAt Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_scanAPsecurityModeAt
#define LLECOM_WIFI_IMPL_scanAPwpsModeAt Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_scanAPwpsModeAt
#define LLECOM_WIFI_IMPL_getCapability Java_ej_ecom_wifi_natives_GenericWifiManagerNatives_getCapability
