/* 
 * Copyright 2014-2016 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by Unknown product - Unknown version - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
typedef struct LLKERNEL LLKERNEL;
#include <stdint.h>
#define LLKERNEL_CONCAT0(p,s) p ## s
#define LLKERNEL_CONCAT(p,s) LLKERNEL_CONCAT0(p,s)
#define LLKERNEL_IMPL_allocate LLKERNEL_CONCAT(LLKERNEL_IMPL,_allocate__I)
#define LLKERNEL_IMPL_free LLKERNEL_CONCAT(LLKERNEL_IMPL,_free__LiceTea_lang_Ram_2)
struct LLKERNEL
{
	int32_t __icetea__id__;
};
LLKERNEL LLKERNEL_getSingleton_instance;

/* 
 * Get the unique instance of this type within the system.
 */
LLKERNEL* LLKERNEL_IMPL_getSingleton(void)
{
	return &LLKERNEL_getSingleton_instance;
}
