#
# Makefile
#
# Copyright 2018-2022 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.
#

PROJECT_NAME := unit_tests

include $(IDF_PATH)/make/project.mk
