#
# Makefile
#
# Copyright 2018-2020 MicroEJ Corp. All rights reserved.
# This library is provided in source code for use, modification and test, subject to license terms.
# Any modification of the source code will break MicroEJ Corp. warranties on the whole library.
#

PROJECT_NAME := microej

include $(IDF_PATH)/make/project.mk
