/* 
 * Copyright 2008-2016 IS2T. All rights reserved.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by Unknown product - Unknown version - DO NOT EDIT IT
 */
/* 
 * Implementation header file. Shall only be included by client implementation C files.
 */
#include <BESTFIT_ALLOCATOR.h>
#include <stdint.h>
#include <intern/BESTFIT_ALLOCATOR_impl.h>
#ifndef BESTFIT_ALLOCATOR_IMPL
#warning "Implementation tag has not been defined. Default implementation tag is BESTFIT_ALLOCATOR_IMPL"
#endif
