/* 
 * C
 * 
 * Copyright 2008-2021 MicroEJ Corp. All rights reserved.
 * This library is provided in source code for use, modification and test, subject to license terms.
 * Any modification of the source code will break MicroEJ Corp. warranties on the whole library.
 */
/* 
 * AUTOGENERATED by Unknown product - Unknown version - DO NOT EDIT IT
 */
/* 
 * Implementation header file. Shall only be included by client implementation C files.
 */
#include <BESTFIT_ALLOCATOR.h>
#include <stdint.h>
#include <intern/BESTFIT_ALLOCATOR_impl.h>
#ifndef BESTFIT_ALLOCATOR_IMPL
#warning "Implementation tag has not been defined. Default implementation tag is BESTFIT_ALLOCATOR_IMPL"
#endif
