/* 
 * IceTea
 * 
 * Copyright 2012-2019 MicroEJ Corp. All rights reserved.
 * MicroEJ Corp. PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by Unknown product - Unknown version - DO NOT EDIT IT
 */
/**
 * Type of display stack's image decoder 
 */
#ifndef _LLDISPLAY_DECODER
#define _LLDISPLAY_DECODER 
#include <intern/LLDISPLAY_DECODER.h>
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
#ifdef __cplusplus
	}
#endif
#endif
